package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * AdmissionNumber generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "admission_number", uniqueConstraints = {
		@UniqueConstraint(columnNames = {"admission_no", "school_code", "sequence"})
		})
public class AdmissionNumberModel implements java.io.Serializable {

	private Long admissionNumberId;
	private String admissionNo;
	private String createdBy;
	private Date createdOn = new Date();
	private long sequence;
	private Set<AdmissionDetailsModel> admissionDetailses = new HashSet<AdmissionDetailsModel>(0);
	private SchoolProfileModel schoolProfile;

	public AdmissionNumberModel() {
	}

	public AdmissionNumberModel(Long admissionNumberId) {
		this.admissionNumberId = admissionNumberId;
	}
	

	public AdmissionNumberModel(String admissionNo, String createdBy,
			Date createdOn, long sequence,
			Set<AdmissionDetailsModel> admissionDetailses) {
		this.admissionNo = admissionNo;
		this.createdBy = createdBy;
		this.createdOn = createdOn;
		this.sequence = sequence;
		this.admissionDetailses = admissionDetailses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "admission_number_id")
	public Long getAdmissionNumberId() {
		return admissionNumberId;
	}

	public void setAdmissionNumberId(Long admissionNumberId) {
		this.admissionNumberId = admissionNumberId;
	}
	
	@Column(name = "admission_no", nullable = false, length = 10)
	public String getAdmissionNo() {
		return this.admissionNo;
	}

	public void setAdmissionNo(String admissionNo) {
		this.admissionNo = admissionNo;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false)
	public SchoolProfileModel getSchoolProfile() {
		return schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}
	
	@Column(name = "created_by", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_on", nullable = false, length = 0)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "sequence", nullable = false)
	public long getSequence() {
		return this.sequence;
	}

	public void setSequence(long sequence) {
		this.sequence = sequence;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionNumber")
	public Set<AdmissionDetailsModel> getAdmissionDetailses() {
		return this.admissionDetailses;
	}

	public void setAdmissionDetailses(Set<AdmissionDetailsModel> admissionDetailses) {
		this.admissionDetailses = admissionDetailses;
	}
	
}
