package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;


/**
 * ClassInformation generated by hbm2java
 */
@Entity
@Table(name = "class_information")
@Cache(usage = CacheConcurrencyStrategy.READ_ONLY, region = "classInfo")
public class ClassInformationModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String classCode;
	private String className;
	private Integer classOrder;

	private Set<AdmissionDetailsModel> admissionDetailses = new HashSet<AdmissionDetailsModel>(0);
	private Set<ClassSectionModel> classSections = new HashSet<ClassSectionModel>(0);
	private Set<ClassFeeCategoryModel> classFeeCategory = new HashSet<ClassFeeCategoryModel>(0);
	private Set<ClassSubjectModel> classSubject = new HashSet<ClassSubjectModel>(0);
	private Set<ReportCardConfigModel> reportCardConfigs = new HashSet<ReportCardConfigModel>(0);

	public ClassInformationModel() {
	}

	public ClassInformationModel(String classCode) {
		this.classCode = classCode;
	}
	public ClassInformationModel(String classCode, String className) {
		this.classCode = classCode;
		this.className = className;
	}

	public ClassInformationModel(String classCode, String className,
			Set<ClassSectionModel> classSections, Set<ClassFeeCategoryModel> classFeeCategory, 
			Set<AdmissionDetailsModel> admissionDetailses, Set<ClassSubjectModel> classSubject) {
		this.classCode = classCode;
		this.className = className;
		this.classSections = classSections;
		this.admissionDetailses = admissionDetailses;
		this.classFeeCategory = classFeeCategory;
		this.classSubject = classSubject;
	}

	@Id
	@Column(name = "class_code", unique = true, nullable = false, length = 5)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "class_name", nullable = false, length = 10)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}
	
	/**
	 * @return the classOrder
	 */
	@Column(name = "class_order", nullable = false)
	public Integer getClassOrder() {
		return classOrder;
	}

	/**
	 * @param classOrder the classOrder to set
	 */
	public void setClassOrder(Integer classOrder) {
		this.classOrder = classOrder;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassSectionModel> getClassSections() {
		return this.classSections;
	}

	public void setClassSections(Set<ClassSectionModel> classSections) {
		this.classSections = classSections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classInformation")
	public Set<AdmissionDetailsModel> getAdmissionDetailses() {
		return this.admissionDetailses;
	}

	public void setAdmissionDetailses(Set<AdmissionDetailsModel> admissionDetailses) {
		this.admissionDetailses = admissionDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassFeeCategoryModel> getClassFeeCategory() {
		return classFeeCategory;
	}

	public void setClassFeeCategory(Set<ClassFeeCategoryModel> classFeeCategory) {
		this.classFeeCategory = classFeeCategory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassSubjectModel> getClassSubject() {
		return classSubject;
	}

	public void setClassSubject(Set<ClassSubjectModel> classSubject) {
		this.classSubject = classSubject;
	}

	/**
	 * @return the reportCardConfigs
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "classInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ReportCardConfigModel> getReportCardConfigs() {
		return reportCardConfigs;
	}

	/**
	 * @param reportCardConfigs the reportCardConfigs to set
	 */
	public void setReportCardConfigs(Set<ReportCardConfigModel> reportCardConfigs) {
		this.reportCardConfigs = reportCardConfigs;
	}
	
	
	
	
	
}
