package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassSectionId generated by hbm2java
 */
@Embeddable
public class ClassFeeCategoryId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String classCode;
	private String sectionCode;
	private String feeCategoryCode;
	private String schoolCode;
	private String sessionCode;

	public ClassFeeCategoryId() {
	}

	public ClassFeeCategoryId(String classCode, String sectionCode, String feeCategoryCode,
			String schoolCode, String sessionCode) {
		this.classCode = classCode;
		this.sectionCode = sectionCode;
		this.feeCategoryCode = feeCategoryCode;
		this.schoolCode = schoolCode;
		this.sessionCode = sessionCode;
	}

	@Column(name = "class_code", nullable = false, length = 5)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}

	@Column(name = "fee_category_code", nullable = false, length = 5)
	public String getFeeCategoryCode() {
		return this.feeCategoryCode;
	}

	public void setFeeCategoryCode(String feeCategoryCode) {
		this.feeCategoryCode = feeCategoryCode;
	}

	@Column(name = "school_code", nullable = false, length = 5)
	public String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}
	
	@Column(name = "session_code", nullable = false, length = 10)
	public String getSessionCode() {
		return sessionCode;
	}

	public void setSessionCode(String sessionCode) {
		this.sessionCode = sessionCode;
	}

	@Column(name = "section_code", nullable = false, length = 5)
	public String getSectionCode() {
		return sectionCode;
	}

	public void setSectionCode(String sectionCode) {
		this.sectionCode = sectionCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((classCode == null) ? 0 : classCode.hashCode());
		result = prime * result
				+ ((feeCategoryCode == null) ? 0 : feeCategoryCode.hashCode());
		result = prime * result
				+ ((schoolCode == null) ? 0 : schoolCode.hashCode());
		result = prime * result
				+ ((sessionCode == null) ? 0 : sessionCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClassFeeCategoryId other = (ClassFeeCategoryId) obj;
		if (classCode == null) {
			if (other.classCode != null)
				return false;
		} else if (!classCode.equals(other.classCode))
			return false;
		if (feeCategoryCode == null) {
			if (other.feeCategoryCode != null)
				return false;
		} else if (!feeCategoryCode.equals(other.feeCategoryCode))
			return false;
		if (schoolCode == null) {
			if (other.schoolCode != null)
				return false;
		} else if (!schoolCode.equals(other.schoolCode))
			return false;
		if (sessionCode == null) {
			if (other.sessionCode != null)
				return false;
		} else if (!sessionCode.equals(other.sessionCode))
			return false;
		return true;
	}

	

}
