package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassSection generated by hbm2java
 */
@Entity
@Table(name = "class_subject")
public class ClassSubjectModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private ClassSubjectId id;
	private ClassInformationModel classInformation;
	private SectionInformationModel sectionInformation;
	private SchoolProfileModel schoolProfile;
	private SubjectDetailsModel subjectDetails;
	private SessionDetailsModel sessionDetails;
	private String type;

	public ClassSubjectModel() {
	}

	public ClassSubjectModel(ClassSubjectId id, ClassInformationModel classInformation, SectionInformationModel sectionInformation,
			SchoolProfileModel schoolProfile, SubjectDetailsModel subjectDetails, SessionDetailsModel sessionDetails, String type) {
		this.id = id;
		this.classInformation = classInformation;
		this.sectionInformation = sectionInformation;
		this.schoolProfile = schoolProfile;
		this.subjectDetails = subjectDetails;
		this.sessionDetails = sessionDetails;
		this.type = type;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "classCode", column = @Column(name = "class_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sectionCode", column = @Column(name = "section_code", nullable = false, length = 5)),
			@AttributeOverride(name = "subjectCode", column = @Column(name = "subject_code", nullable = false, length = 5)),
			@AttributeOverride(name = "schoolCode", column = @Column(name = "school_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sessionCode", column = @Column(name = "session_code", nullable = false, length = 10)) })
	public ClassSubjectId getId() {
		return this.id;
	}

	public void setId(ClassSubjectId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_code", nullable = false, insertable = false, updatable = false)
	public ClassInformationModel getClassInformation() {
		return this.classInformation;
	}

	public void setClassInformation(ClassInformationModel classInformation) {
		this.classInformation = classInformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false, insertable = false, updatable = false)
	public SchoolProfileModel getSchoolProfile() {
		return this.schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subject_code", nullable = false, insertable = false, updatable = false)
	public SubjectDetailsModel getSubjectDetails() {
		return this.subjectDetails;
	}

	public void setSubjectDetails(SubjectDetailsModel subjectDetails) {
		this.subjectDetails = subjectDetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_code", nullable = false, insertable = false, updatable = false)
	public SectionInformationModel getSectionInformation() {
		return sectionInformation;
	}

	public void setSectionInformation(SectionInformationModel sectionInformation) {
		this.sectionInformation = sectionInformation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_code", nullable = false, insertable = false, updatable = false)
	public SessionDetailsModel getSessionDetails() {
		return sessionDetails;
	}

	public void setSessionDetails(SessionDetailsModel sessionDetails) {
		this.sessionDetails = sessionDetails;
	}

	@Column(name = "type", nullable = false, length = 2)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	
	
}
