package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClassSection generated by hbm2java
 */
@Entity
@Table(name = "class_fee_category")
public class ClassFeeCategoryModel implements java.io.Serializable, EntityModel {

	private static final long serialVersionUID = 1L;
	private ClassFeeCategoryId id;
	private ClassInformationModel classInformation;
	private SectionInformationModel sectionInformation;
	private SchoolProfileModel schoolProfile;
	private SessionDetailsModel sessionDetails;
	private FeeCategoryModel feeCategory;
	private String type;
	private String feeType;
	private String status;
	private BigDecimal amount;
	
	
	public ClassFeeCategoryModel() {
	}

	public ClassFeeCategoryModel(ClassFeeCategoryId id, ClassInformationModel classInformation, SectionInformationModel sectionInformation,
			SchoolProfileModel schoolProfile, FeeCategoryModel feeCategory, String type,
			BigDecimal amount, SessionDetailsModel sessionDetails) {
		this.id = id;
		this.classInformation = classInformation;
		this.sectionInformation = sectionInformation;
		this.schoolProfile = schoolProfile;
		this.sessionDetails = sessionDetails;
		this.feeCategory = feeCategory;
		this.type = type;
		this.amount = amount;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "classCode", column = @Column(name = "class_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sectionCode", column = @Column(name = "section_code", nullable = false, length = 5)),
			@AttributeOverride(name = "feeCategoryCode", column = @Column(name = "fee_category_code", nullable = false, length = 5)),
			@AttributeOverride(name = "schoolCode", column = @Column(name = "school_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sessionCode", column = @Column(name = "session_code", nullable = false, length = 10))})
	public ClassFeeCategoryId getId() {
		return this.id;
	}

	public void setId(ClassFeeCategoryId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_code", nullable = false, insertable = false, updatable = false)
	public ClassInformationModel getClassInformation() {
		return this.classInformation;
	}

	public void setClassInformation(ClassInformationModel classInformation) {
		this.classInformation = classInformation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_code", nullable = false, insertable = false, updatable = false)
	public SectionInformationModel getSectionInformation() {
		return this.sectionInformation;
	}

	public void setSectionInformation(SectionInformationModel sectionInformation) {
		this.sectionInformation = sectionInformation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_code", nullable = false, insertable = false, updatable = false)
	public SessionDetailsModel getSessionDetails() {
		return sessionDetails;
	}

	public void setSessionDetails(SessionDetailsModel sessionDetails) {
		this.sessionDetails = sessionDetails;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false, insertable = false, updatable = false)
	public SchoolProfileModel getSchoolProfile() {
		return this.schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fee_category_code", nullable = false, insertable = false, updatable = false)
	public FeeCategoryModel getFeeCategory() {
		return this.feeCategory;
	}

	public void setFeeCategory(FeeCategoryModel feeCategory) {
		this.feeCategory = feeCategory;
	}

	@Column(name = "type", nullable = false, length = 2)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}
	
	/**
	 * @return the status
	 */
	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the feeType
	 */
	@Column(name = "fee_type", nullable = false, length = 2)
	public String getFeeType() {
		return feeType;
	}

	/**
	 * @param feeType the feeType to set
	 */
	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}

	@Column(name = "amount", nullable = false, precision = 8, scale = 2)
	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	
	
}
