package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClassSectionId generated by hbm2java
 */
@Embeddable
public class ClassSubjectId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String classCode;
	private String sectionCode;
	private String subjectCode;
	private String schoolCode;
	private String sessionCode;

	public ClassSubjectId() {
	}

	public ClassSubjectId(String classCode, String sectionCode, String subjectCode,
			String schoolCode, String sessionCode) {
		this.classCode = classCode;
		this.sectionCode = sectionCode;
		this.subjectCode = subjectCode;
		this.schoolCode = schoolCode;
		this.sessionCode = sessionCode;
	}

	@Column(name = "class_code", nullable = false, length = 5)
	public String getClassCode() {
		return this.classCode;
	}

	public void setClassCode(String classCode) {
		this.classCode = classCode;
	}
	
	@Column(name = "section_code", nullable = false, length = 5)
	public String getSectionCode() {
		return sectionCode;
	}

	public void setSectionCode(String sectionCode) {
		this.sectionCode = sectionCode;
	}

	@Column(name = "subject_code", nullable = false, length = 5)
	public String getSubjectCode() {
		return this.subjectCode;
	}

	public void setSubjectCode(String subjectCode) {
		this.subjectCode = subjectCode;
	}

	@Column(name = "school_code", nullable = false, length = 5)
	public String getSchoolCode() {
		return this.schoolCode;
	}

	public void setSchoolCode(String schoolCode) {
		this.schoolCode = schoolCode;
	}

	@Column(name = "session_code", nullable = false, length = 10)
	public String getSessionCode() {
		return sessionCode;
	}

	public void setSessionCode(String sessionCode) {
		this.sessionCode = sessionCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((classCode == null) ? 0 : classCode.hashCode());
		result = prime * result
				+ ((schoolCode == null) ? 0 : schoolCode.hashCode());
		result = prime * result
				+ ((sectionCode == null) ? 0 : sectionCode.hashCode());
		result = prime * result
				+ ((sessionCode == null) ? 0 : sessionCode.hashCode());
		result = prime * result
				+ ((subjectCode == null) ? 0 : subjectCode.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClassSubjectId other = (ClassSubjectId) obj;
		if (classCode == null) {
			if (other.classCode != null)
				return false;
		} else if (!classCode.equals(other.classCode))
			return false;
		if (schoolCode == null) {
			if (other.schoolCode != null)
				return false;
		} else if (!schoolCode.equals(other.schoolCode))
			return false;
		if (sectionCode == null) {
			if (other.sectionCode != null)
				return false;
		} else if (!sectionCode.equals(other.sectionCode))
			return false;
		if (sessionCode == null) {
			if (other.sessionCode != null)
				return false;
		} else if (!sessionCode.equals(other.sessionCode))
			return false;
		if (subjectCode == null) {
			if (other.subjectCode != null)
				return false;
		} else if (!subjectCode.equals(other.subjectCode))
			return false;
		return true;
	}
	
	
	

}
