package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FeeCategory generated by hbm2java
 */
@Entity
@Table(name = "fee_category")
public class FeeCategoryModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String feeCategoryCode;
	private String feeCategoryName;

	private Set<ClassFeeCategoryModel> classFeeCategory = new HashSet<ClassFeeCategoryModel>(0);

	public FeeCategoryModel() {
	}

	public FeeCategoryModel(String feeCategoryCode) {
		this.feeCategoryCode = feeCategoryCode;
	}
	
	public FeeCategoryModel(String feeCategoryCode, String feeCategoryName) {
		this.feeCategoryCode = feeCategoryCode;
		this.feeCategoryName = feeCategoryName;
	}

	public FeeCategoryModel(String feeCategoryCode, String feeCategoryName,
			Set<ClassFeeCategoryModel> classFeeCategory) {
		this.feeCategoryCode = feeCategoryCode;
		this.feeCategoryName = feeCategoryName;
		this.classFeeCategory = classFeeCategory;
	}

	@Id
	@Column(name = "fee_category_code", unique = true, nullable = false, length = 5)
	public String getFeeCategoryCode() {
		return this.feeCategoryCode;
	}

	public void setFeeCategoryCode(String feeCategoryCode) {
		this.feeCategoryCode = feeCategoryCode;
	}

	@Column(name = "fee_category_name", nullable = false, length = 50)
	public String getFeeCategoryName() {
		return this.feeCategoryName;
	}

	public void setFeeCategoryName(String feeCategoryName) {
		this.feeCategoryName = feeCategoryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "feeCategory", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassFeeCategoryModel> getClassFeeCategory() {
		return this.classFeeCategory;
	}

	public void setClassFeeCategory(Set<ClassFeeCategoryModel> classFeeCategory) {
		this.classFeeCategory = classFeeCategory;
	}

	
}
