package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GlobalConfig generated by hbm2java
 */

@Entity
@Table(name = "micro_service_config")
public class MicroServiceConfigModel implements EntityModel {

	private static final long serialVersionUID = 9154474006516128373L;
	private String configCode;
	private String configDescription;
	private String configValue;

	public MicroServiceConfigModel() {
	}

	public MicroServiceConfigModel(String configCode, String configValue) {
		this.configCode = configCode;
		this.configValue = configValue;
	}

	public MicroServiceConfigModel(String configCode, String configValue, String configDescription) {
		this.configCode = configCode;
		this.configValue = configValue;
		this.configDescription = configDescription;
	}

	@Id
	@Column(name = "config_code", nullable = false, length = 50)
	public String getConfigCode() {
		return this.configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	@Column(name = "config_value", nullable = false)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	@Column(name = "config_description")
	public String getConfigDescription() {
		return this.configDescription;
	}

	public void setConfigDescription(String configDescription) {
		this.configDescription = configDescription;
	}

}
