package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * ParentDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "parent_details")
public class ParentDetailsModel implements java.io.Serializable, EntityModel {

	private Long parentDetailsId;
	private String fatherEmail;
	private String fatherMobile;
	private String fatherName;
	private String fatherOccupation;
	private String motherEmail;
	private String motherMobile;
	private String motherName;
	private String motherOccupation;
	private String parentAddress;
	private String fatherFirstName;
	private String fatherImage;
	private String fatherLastName;
	private String fatherMiddleName;
	private StudentDetailsModel studentDetails;
	private UserDetailsModel userDetails;

	public ParentDetailsModel() {
	}

	public ParentDetailsModel(Long parentDetailsId, String fatherName,
			String motherName) {
		this.parentDetailsId = parentDetailsId;
		this.fatherName = fatherName;
		this.motherName = motherName;
	}
	
	

	public ParentDetailsModel(Long parentDetailsId) {
		this.parentDetailsId = parentDetailsId;
	}

	public ParentDetailsModel(Long parentDetailsId, String fatherEmail,
			String fatherMobile, String fatherName, String fatherOccupation,
			String motherEmail, String motherMobile, String motherName,
			String motherOccupation, String parentAddress, StudentDetailsModel studentDetails, UserDetailsModel userDetails) {
		this.parentDetailsId = parentDetailsId;
		this.fatherEmail = fatherEmail;
		this.fatherMobile = fatherMobile;
		this.fatherName = fatherName;
		this.fatherOccupation = fatherOccupation;
		this.motherEmail = motherEmail;
		this.motherMobile = motherMobile;
		this.motherName = motherName;
		this.motherOccupation = motherOccupation;
		this.parentAddress = parentAddress;
		this.userDetails = userDetails;
		
		this.studentDetails = studentDetails;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "parent_details_id", unique = true, nullable = false)
	public Long getParentDetailsId() {
		return this.parentDetailsId;
	}

	public void setParentDetailsId(Long parentDetailsId) {
		this.parentDetailsId = parentDetailsId;
	}

	@Column(name = "father_email", length = 50)
	public String getFatherEmail() {
		return this.fatherEmail;
	}

	public void setFatherEmail(String fatherEmail) {
		this.fatherEmail = fatherEmail;
	}

	@Column(name = "father_mobile", length = 15)
	public String getFatherMobile() {
		return this.fatherMobile;
	}

	public void setFatherMobile(String fatherMobile) {
		this.fatherMobile = fatherMobile;
	}


	@Column(name = "father_occupation", length = 50)
	public String getFatherOccupation() {
		return this.fatherOccupation;
	}

	public void setFatherOccupation(String fatherOccupation) {
		this.fatherOccupation = fatherOccupation;
	}

	@Column(name = "mother_email", length = 50)
	public String getMotherEmail() {
		return this.motherEmail;
	}

	public void setMotherEmail(String motherEmail) {
		this.motherEmail = motherEmail;
	}

	@Column(name = "mother_mobile", length = 15)
	public String getMotherMobile() {
		return this.motherMobile;
	}

	public void setMotherMobile(String motherMobile) {
		this.motherMobile = motherMobile;
	}

	@Column(name = "mother_name", nullable = false, length = 50)
	public String getMotherName() {
		return this.motherName;
	}

	public void setMotherName(String motherName) {
		this.motherName = motherName;
	}

	@Column(name = "mother_occupation", length = 50)
	public String getMotherOccupation() {
		return this.motherOccupation;
	}

	public void setMotherOccupation(String motherOccupation) {
		this.motherOccupation = motherOccupation;
	}

	@Column(name = "parent_address")
	public String getParentAddress() {
		return this.parentAddress;
	}

	public void setParentAddress(String parentAddress) {
		this.parentAddress = parentAddress;
	}

	@Column(name = "father_first_name", nullable = false, length = 50)
	public String getFatherFirstName() {
		return fatherFirstName;
	}

	public void setFatherFirstName(String fatherFirstName) {
		this.fatherFirstName = fatherFirstName;
	}


	@Column(name = "father_image", length = 50)
	public String getFatherImage() {
		return fatherImage;
	}

	public void setFatherImage(String fatherImage) {
		this.fatherImage = fatherImage;
	}


	@Column(name = "father_last_name", nullable = false, length = 50)
	public String getFatherLastName() {
		return fatherLastName;
	}

	public void setFatherLastName(String fatherLastName) {
		this.fatherLastName = fatherLastName;
	}


	@Column(name = "father_middle_name", length = 50)
	public String getFatherMiddleName() {
		return fatherMiddleName;
	}

	public void setFatherMiddleName(String fatherMiddleName) {
		this.fatherMiddleName = fatherMiddleName;
	}

	@OneToOne(mappedBy = "parentDetails", fetch = FetchType.LAZY)
	public StudentDetailsModel getStudentDetails() {
		return studentDetails;
	}

	public void setStudentDetails(StudentDetailsModel studentDetails) {
		this.studentDetails = studentDetails;
	}

	@OneToOne(mappedBy = "parentDetails", fetch = FetchType.LAZY)	
	public UserDetailsModel getUserDetails() {
		return userDetails;
	}

	public void setUserDetails(UserDetailsModel userDetails) {
		this.userDetails = userDetails;
	}

	@Transient
	public String getFatherName() {
		if(!"".equals(this.fatherMiddleName) && this.fatherMiddleName != null)
		{
			this.fatherName = this.fatherFirstName + " " + this.fatherMiddleName + " " + this.fatherLastName;
		}
		else
		{
			this.fatherName = this.fatherFirstName + " " + this.fatherLastName;
		}
		return this.fatherName;
	}

	public void setFatherName(String fatherName) {
		this.fatherName = fatherName;
	}

	
}
