package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * GlobalConfig generated by hbm2java
 */

@Entity
@Table(name = "REPORT_CARD_CONFIG")
public class ReportCardConfigModel implements EntityModel {

	private static final long serialVersionUID = 9154474006516128373L;
	private String configCode;
	private String configDescription;
	private String configValue;
	private SchoolProfileModel schoolProfile;
	private SessionDetailsModel sessionDetails;
	private ClassInformationModel classInformation;
	private SectionInformationModel sectionInformation;

	public ReportCardConfigModel() {
	}

	public ReportCardConfigModel(String configCode, String configValue) {
		this.configCode = configCode;
		this.configValue = configValue;
	}

	public ReportCardConfigModel(String configCode, String configDescription,
			String configValue, SchoolProfileModel schoolProfile) {
		this.configCode = configCode;
		this.configDescription = configDescription;
		this.configValue = configValue;
		this.schoolProfile = schoolProfile;
	}

	@Id
	@Column(name = "config_code", nullable = false, length = 5)
	public String getConfigCode() {
		return this.configCode;
	}

	public void setConfigCode(String configCode) {
		this.configCode = configCode;
	}

	@Column(name = "config_description")
	public String getConfigDescription() {
		return this.configDescription;
	}

	public void setConfigDescription(String configDescription) {
		this.configDescription = configDescription;
	}

	@Column(name = "config_value", nullable = false, length = 150)
	public String getConfigValue() {
		return this.configValue;
	}

	public void setConfigValue(String configValue) {
		this.configValue = configValue;
	}

	@Id
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false)
	public SchoolProfileModel getSchoolProfile() {
		return schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}


	@Id
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_code", insertable = false, updatable = false)
	public SessionDetailsModel getSessionDetails() {
		return sessionDetails;
	}

	public void setSessionDetails(SessionDetailsModel sessionDetails) {
		this.sessionDetails = sessionDetails;
	}
	

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_code")
	public ClassInformationModel getClassInformation() {
		return this.classInformation;
	}

	public void setClassInformation(ClassInformationModel classInformation) {
		this.classInformation = classInformation;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section_code")
	public SectionInformationModel getSectionInformation() {
		return this.sectionInformation;
	}

	public void setSectionInformation(SectionInformationModel sectionInformation) {
		this.sectionInformation = sectionInformation;
	}
}
