package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolSession generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "school_session")
public class SchoolSessionModel implements java.io.Serializable {

	private Integer schoolSessionId;
	private int sequence;
	private String status;
	private SessionDetailsModel sessionDetails;
	private SchoolProfileModel schoolProfile;

	public SchoolSessionModel() {
	}


	public SchoolSessionModel(int sequence, String status, SessionDetailsModel sessionDetails, SchoolProfileModel schoolProfile) {
		this.sequence = sequence;
		this.status = status;
		this.sessionDetails = sessionDetails;
		this.schoolProfile = schoolProfile;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "school_session_id", unique = true, nullable = false)
	public Integer getSchoolSessionId() {
		return schoolSessionId;
	}

	public void setSchoolSessionId(Integer schoolSessionId) {
		this.schoolSessionId = schoolSessionId;
	}

	@Column(name = "sequence", nullable = false)
	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_code", nullable = false)
	public SessionDetailsModel getSessionDetails() {
		return sessionDetails;
	}


	public void setSessionDetails(SessionDetailsModel sessionDetails) {
		this.sessionDetails = sessionDetails;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false)
	public SchoolProfileModel getSchoolProfile() {
		return schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}

	
	
	
}
