package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SchoolSession generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "school_payment_category")
public class SchoolPaymentCategoryModel implements java.io.Serializable {

	private Integer schoolPaymentCategoryId;
	private SessionDetailsModel sessionDetails;
	private SchoolProfileModel schoolProfile;
	private PaymentCategoryModel paymentCategory;

	public SchoolPaymentCategoryModel() {
	}


	public SchoolPaymentCategoryModel(SessionDetailsModel sessionDetails, SchoolProfileModel schoolProfile, PaymentCategoryModel paymentCategory) {
		this.sessionDetails = sessionDetails;
		this.schoolProfile = schoolProfile;
		this.paymentCategory = paymentCategory;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "school_payment_category_id", unique = true, nullable = false)
	public Integer getSchoolPaymentCategoryId() {
		return schoolPaymentCategoryId;
	}

	public void setSchoolPaymentCategoryId(Integer schoolPaymentCategoryId) {
		this.schoolPaymentCategoryId = schoolPaymentCategoryId;
	}	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "session_code", nullable = false)
	public SessionDetailsModel getSessionDetails() {
		return sessionDetails;
	}


	public void setSessionDetails(SessionDetailsModel sessionDetails) {
		this.sessionDetails = sessionDetails;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "school_code", nullable = false)
	public SchoolProfileModel getSchoolProfile() {
		return schoolProfile;
	}

	public void setSchoolProfile(SchoolProfileModel schoolProfile) {
		this.schoolProfile = schoolProfile;
	}


	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payment_category_code", nullable = false)
	public PaymentCategoryModel getPaymentCategory() {
		return paymentCategory;
	}


	public void setPaymentCategory(PaymentCategoryModel paymentCategory) {
		this.paymentCategory = paymentCategory;
	}

	
	
	
}
