package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SectionInformation generated by hbm2java
 */
@Entity
@Table(name = "section_information")
public class SectionInformationModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private String sectionCode;
	private String sectionName;
	private Set<AdmissionDetailsModel> admissionDetailses = new HashSet<AdmissionDetailsModel>(0);
	private Set<ClassSectionModel> classSections = new HashSet<ClassSectionModel>(0);
	private Set<ClassSubjectModel> classSubject = new HashSet<ClassSubjectModel>(0);
	private Set<ClassFeeCategoryModel> classFeeCategory = new HashSet<ClassFeeCategoryModel>(0);
	private Set<ReportCardConfigModel> reportCardConfigs = new HashSet<ReportCardConfigModel>(0);

	public SectionInformationModel() {
	}

	public SectionInformationModel(String sectionCode) {
		this.sectionCode = sectionCode;
	}
	
	public SectionInformationModel(String sectionCode, String sectionName) {
		this.sectionCode = sectionCode;
		this.sectionName = sectionName;
	}

	public SectionInformationModel(String sectionCode, String sectionName, Set<ClassFeeCategoryModel> classFeeCategory,
			Set<ClassSectionModel> classSections, Set<AdmissionDetailsModel> admissionDetailses, Set<ClassSubjectModel> classSubject) {
		this.sectionCode = sectionCode;
		this.sectionName = sectionName;
		this.classSections = classSections;
		this.admissionDetailses = admissionDetailses;
		this.classSubject = classSubject;
		this.classFeeCategory = classFeeCategory;
	}

	@Id
	@Column(name = "section_code", unique = true, nullable = false, length = 5)
	public String getSectionCode() {
		return this.sectionCode;
	}

	public void setSectionCode(String sectionCode) {
		this.sectionCode = sectionCode;
	}

	@Column(name = "section_name", nullable = false, length = 10)
	public String getSectionName() {
		return this.sectionName;
	}

	public void setSectionName(String sectionName) {
		this.sectionName = sectionName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectionInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassSectionModel> getClassSections() {
		return this.classSections;
	}

	public void setClassSections(Set<ClassSectionModel> classSections) {
		this.classSections = classSections;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectionInformation")
	public Set<AdmissionDetailsModel> getAdmissionDetailses() {
		return this.admissionDetailses;
	}

	public void setAdmissionDetailses(Set<AdmissionDetailsModel> admissionDetailses) {
		this.admissionDetailses = admissionDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectionInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassSubjectModel> getClassSubject() {
		return classSubject;
	}

	public void setClassSubject(Set<ClassSubjectModel> classSubject) {
		this.classSubject = classSubject;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectionInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ClassFeeCategoryModel> getClassFeeCategory() {
		return classFeeCategory;
	}

	public void setClassFeeCategory(Set<ClassFeeCategoryModel> classFeeCategory) {
		this.classFeeCategory = classFeeCategory;
	}

	/**
	 * @return the reportCardConfigs
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sectionInformation", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<ReportCardConfigModel> getReportCardConfigs() {
		return reportCardConfigs;
	}

	/**
	 * @param reportCardConfigs the reportCardConfigs to set
	 */
	public void setReportCardConfigs(Set<ReportCardConfigModel> reportCardConfigs) {
		this.reportCardConfigs = reportCardConfigs;
	}
	
	
}
