package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SessionDetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "session_details")
public class SessionDetailsModel implements java.io.Serializable {

	private String sessionCode;
	private String sessionName;
	private Set<SchoolSessionModel> schoolSessions = new HashSet<SchoolSessionModel>(
			0);
	private Set<AdmissionDetailsModel> admissionDetailses = new HashSet<AdmissionDetailsModel>(
			0);
	private Set<UserCheckInModel> userAttendances = new HashSet<UserCheckInModel>(
			0);
	private Set<ClassSectionModel> classSections = new HashSet<ClassSectionModel>(
			0);
	private Set<ClassSubjectModel> classSubjects = new HashSet<ClassSubjectModel>(
			0);
	private Set<SchoolPaymentCategoryModel> schoolPaymentCategories = new HashSet<SchoolPaymentCategoryModel>(
			0);
	private Set<ReportCardConfigModel> reportCardConfigs = new HashSet<ReportCardConfigModel>(
			0);

	public SessionDetailsModel() {
	}

	public SessionDetailsModel(String sessionCode) {
		this.sessionCode = sessionCode;
	}



	public SessionDetailsModel(Set<SchoolSessionModel> schoolSessions, Set<AdmissionDetailsModel> admissionDetailses, 
			Set<UserCheckInModel> userAttendances, Set<ClassSectionModel> classSections,
			Set<ClassSubjectModel> classSubjects, Set<SchoolPaymentCategoryModel> schoolPaymentCategories) {
		this.schoolSessions = schoolSessions;
		this.admissionDetailses = admissionDetailses;
		this.userAttendances = userAttendances;
		this.classSections = classSections;
		this.classSubjects = classSubjects;
		this.schoolPaymentCategories = schoolPaymentCategories;
	}

	@Id
	@Column(name = "session_code", unique = true, nullable = false, length = 10)
	public String getSessionCode() {
		return sessionCode;
	}

	public void setSessionCode(String sessionCode) {
		this.sessionCode = sessionCode;
	}

	@Column(name = "session_name", unique = true, nullable = false, length = 15)
	public String getSessionName() {
		return sessionName;
	}

	public void setSessionName(String sessionName) {
		this.sessionName = sessionName;
	}
	
	
	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<AdmissionDetailsModel> getAdmissionDetailses() {
		return this.admissionDetailses;
	}

	public void setAdmissionDetailses(Set<AdmissionDetailsModel> admissionDetailses) {
		this.admissionDetailses = admissionDetailses;
	}


	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<UserCheckInModel> getUserAttendances() {
		return userAttendances;
	}

	public void setUserAttendances(Set<UserCheckInModel> userAttendances) {
		this.userAttendances = userAttendances;
	}

	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<SchoolSessionModel> getSchoolSessions() {
		return schoolSessions;
	}

	public void setSchoolSessions(Set<SchoolSessionModel> schoolSessions) {
		this.schoolSessions = schoolSessions;
	}

	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<ClassSectionModel> getClassSections() {
		return classSections;
	}

	public void setClassSections(Set<ClassSectionModel> classSections) {
		this.classSections = classSections;
	}

	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<ClassSubjectModel> getClassSubjects() {
		return classSubjects;
	}

	public void setClassSubjects(Set<ClassSubjectModel> classSubjects) {
		this.classSubjects = classSubjects;
	}

	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<SchoolPaymentCategoryModel> getSchoolPaymentCategories() {
		return schoolPaymentCategories;
	}

	public void setSchoolPaymentCategories(Set<SchoolPaymentCategoryModel> schoolPaymentCategories) {
		this.schoolPaymentCategories = schoolPaymentCategories;
	}

	/**
	 * @return the reportCardConfigs
	 */
	@OneToMany(mappedBy = "sessionDetails", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	public Set<ReportCardConfigModel> getReportCardConfigs() {
		return reportCardConfigs;
	}

	/**
	 * @param reportCardConfigs the reportCardConfigs to set
	 */
	public void setReportCardConfigs(Set<ReportCardConfigModel> reportCardConfigs) {
		this.reportCardConfigs = reportCardConfigs;
	}

	
	
	
	
}
