package com.school.common.model;

// Generated Jul 5, 2016 5:14:02 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClassSection generated by hbm2java
 */
@Entity
@Table(name = "student_attendance_history")
public class StudentAttendanceHistoryModel implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private StudentAttendanceHistoryId studentAttendanceHistoryId;
	private int totalTransaction;

	public StudentAttendanceHistoryModel() {
	}

	public StudentAttendanceHistoryModel(StudentAttendanceHistoryId studentAttendanceHistoryId) {
		this.studentAttendanceHistoryId = studentAttendanceHistoryId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schoolCode", column = @Column(name = "school_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sessionCode", column = @Column(name = "session_code", nullable = false, length = 10)),
			@AttributeOverride(name = "classCode", column = @Column(name = "class_code", nullable = false, length = 5)),
			@AttributeOverride(name = "sectionCode", column = @Column(name = "section_code", nullable = false, length = 5)),
			@AttributeOverride(name = "month", column = @Column(name = "month", nullable = false))})
	public StudentAttendanceHistoryId getStudentAttendanceHistoryId() {
		return studentAttendanceHistoryId;
	}

	public void setStudentAttendanceHistoryId(
			StudentAttendanceHistoryId studentAttendanceHistoryId) {
		this.studentAttendanceHistoryId = studentAttendanceHistoryId;
	}

	@Column(name = "total_transaction", nullable = false)
	public int getTotalTransaction() {
		return totalTransaction;
	}

	public void setTotalTransaction(int totalTransaction) {
		this.totalTransaction = totalTransaction;
	}

	
	
}
