package com.school.common.model;

// Generated Apr 2, 2016 3:30:20 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsersRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRoleModel implements java.io.Serializable, EntityModel {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6678891599295092161L;
	private String userRoleId;
	private String userRoleName;
	private Set<UserModel> users = new HashSet<UserModel>(0);

	public UserRoleModel() {
	}

	public UserRoleModel(String userRoleId) {
		this.userRoleId = userRoleId;
	}

	public UserRoleModel(String userRoleId, String userRoleName, Set<UserModel> users) {
		this.userRoleId = userRoleId;
		this.userRoleName = userRoleName;
		this.users = users;
	}

	@Id
	@Column(name = "user_role_id", unique = true, nullable = false, length = 15)
	public String getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(String usersRoleId) {
		this.userRoleId = usersRoleId;
	}

	@Column(name = "user_role_name", nullable = false, length = 50)
	public String getUserRoleName() {
		return this.userRoleName;
	}

	public void setUserRoleName(String userRoleName) {
		this.userRoleName = userRoleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userRole")
	public Set<UserModel> getUsers() {
		return this.users;
	}

	public void setUsers(Set<UserModel> users) {
		this.users = users;
	}

}
